logging.level.org.springframework.security=DEBUG
spring.application.name=backend
server.servlet.context-path=/api/v1
jwt.secret=M9GBjAZzVEUnJZEUCr8/EFJl06caZ+jnukGd4J/PO3dtYeeRfvOEFZQbIU4mFxwyuJI8wYn/0RH1TEMXK0OR2Q==
jwt.expiration=86400000